### ISSUE TITLE
BigDecimal Default Format no .00

### ISSUE THREAD

**Issue by ijiangtao** [venusdrogon/feilong-json#24]
如下截图，BigDecimal 在Log中，如果小数点后为.00 , .00会不输出 ： 

![image](https://user-images.githubusercontent.com/28173035/45604763-457e3980-ba6a-11e8-914e-97402b252c04.png)

**Comment by venusdrogon** [comment]
![image](https://user-images.githubusercontent.com/3479472/51088274-85df9100-1798-11e9-95ec-2726cd5a362b.png)

**Comment by venusdrogon** [comment]
![image](https://user-images.githubusercontent.com/3479472/51099093-9ed45a80-1809-11e9-9e74-e8ed98f82f92.png)

net.sf.json.AbstractJSON line 268

**Comment by venusdrogon** [comment]
com.feilong.json.jsonlib.processor.BigDecimalJsonValueProcessor

BigDecimal数字json value处理器.

如果不使用这个处理器,对于 BigDecimal格式输出成json,在json to string 字符串的时候,会剔除末尾的0和小数点,会出现循环截断的情况,参见 net.sf.json.util.JSONUtils.numberToString(Number):

示例:
 User user = new User("feilong1", 24);
 user.setMoney(toBigDecimal("99999999.00"));
 
 JavaToJsonConfig javaToJsonConfig = new JavaToJsonConfig();
 javaToJsonConfig.setIncludes("name", "age", "money");
 
 LOGGER.debug(JsonUtil.format(user, javaToJsonConfig));
 
返回:
 {
 "age": 24,
 "name": "feilong1",
 "money": 99999999
 }
 
可以看出,money少了后面的 .00

此时,你可以使用该处理器,提前先把结果处理成字符串,这样就避免进行后面toString 的时候将number 转成字符串的过程

示例:
 User user = new User("feilong1", 24);
 user.setMoney(toBigDecimal("99999999.00"));
 
 Map<String, JsonValueProcessor> propertyNameAndJsonValueProcessorMap = new HashMap<>();
 propertyNameAndJsonValueProcessorMap.put("money", BigDecimalJsonValueProcessor.DEFAULT_INSTANCE);
 
 JavaToJsonConfig javaToJsonConfig = new JavaToJsonConfig();
 javaToJsonConfig.setPropertyNameAndJsonValueProcessorMap(propertyNameAndJsonValueProcessorMap);
 javaToJsonConfig.setIncludes("name", "age", "money");
 
 LOGGER.debug(JsonUtil.format(user, javaToJsonConfig));
 
返回:
 {
 "age": 24,
 "name": "feilong1",
 "money": "99999999.00"
 }

**Comment by venusdrogon** [comment]
![image](https://user-images.githubusercontent.com/3479472/51099555-671ae200-180c-11e9-8155-e947975e92e4.png)


将根据 实际设置的精度来 显示
